New Feature: Adding Liquidity Pool Indexing for Moxie
moxie-protocol/Subgraphs pull request #44
Opened 2024-09-09 06:37 UTC by Hrishikesh-Thakkar

## Feature Description
The scope of this PR is to index 2 Liquidity Pools which are both based on Uniswap V2 Contracts

1. [Uniswap](https://basescan.org/address/0x493ad7e1c509de7c89e1963fe9005ead49fdd19c) (Moxie-USDC)
2. [Aerodrome](https://basescan.org/address/0xc02Dc3a9b6eaD739C56CDEa716D8fEC4Ffe4C799) (Moxie-WETH)

## Data Points Being Indexed
1. Reserves of both tokens in the Liquidity Pool
2. Total Supply of LP Tokens
3. Individual Balances of LP Tokens for each user
4. In the case of Aerodrome index the [LP Staking ](https://basescan.org/address/0xea2c1c05c17eed888d0027f17ee23637dff66feb) as well.

## Solution
1. To capture the balances and total supply with minimal RPC calls all the transfers of the LP Token are tracked.  
    Event: `Transfer(indexed address,indexed address,uint256)`
2. To capture the Reserves in both LPs we track the following event
    Event: `Sync(uint256,uint256)`  & `  Sync(uint112,uint112)`
3. To capture the Staking Contract related transactions we are capturing
    Event: `Deposit(indexed address,indexed address,uint256)` & `Withdraw(indexed address,uint256)`

2024-09-10 09:47 UTC, sharathkrml approved these changes

2024-09-11 00:31 UTC, 0xsarvesh requested changes

2024-09-11 00:31 UTC, 0xsarvesh commented on moxie-liquidity-pool/schema.graphql
> +  unstakedLpAmount: BigInt!
can you add a field for totalLPAmount

2024-09-11 00:31 UTC, 0xsarvesh commented on moxie-liquidity-pool/src/utils.ts
> +  let sender = getOrCreateUserEntity(event, from.toHexString())
check for zero from & to address. No need to track for zero address lp balance

2024-09-11 00:31 UTC, 0xsarvesh commented on moxie-liquidity-pool/src/utils.ts
> +  senderUserPool.unstakedLpAmount = senderUserPool.unstakedLpAmount.minus(amount)
Similar comment, don't track for zero address.

2024-09-11 06:07 UTC, Hrishikesh-Thakkar commented on moxie-liquidity-pool/schema.graphql
> +  unstakedLpAmount: BigInt!
done

2024-09-11 16:09 UTC, 0xsarvesh approved these changes

2024-09-11 16:09 UTC, merged